const TopMonth = [
    {
        id: 1,
        name: 'Võ Luyện Đỉnh Phong',
        chapter: '2265',
        view: '29.280.039',
        img: 'https://st.nettruyenco.com/data/comics/32/vo-luyen-dinh-phong.jpg',
        href: '',
    },
    {
        id: 2,
        name: 'Ta Có Một Sơn Trại',
        chapter: '343',
        view: '7.122.760',
        img: 'https://st.nettruyenco.com/data/comics/217/ta-co-mot-son-trai.jpg',
        href: '',
    },
    {
        id: 3,
        name: 'Đại Vương Tha Mạng',
        chapter: '495',
        view: '6.138.564',
        img: 'https://st.nettruyenco.com/data/comics/131/dai-vuong-tha-mang.jpg',
        href: '',
    },
    {
        id: 4,
        name: 'Trọng Sinh Đô Thị Tu Tiên',
        chapter: '767',
        view: '5.942.081',
        img: 'https://st.nettruyenco.com/data/comics/213/trong-sinh-do-thi-tu-tien.jpg',
        href: '',
    },
    {
        id: 5,
        name: 'Tu La Võ Thần',
        chapter: '568',
        view: '5.618.704',
        img: 'https://st.nettruyenco.com/data/comics/43/tu-la-vo-than.jpg',
        href: '',
    },
    {
        id: 6,
        name: 'Toàn Chức Pháp Sư',
        chapter: '568',
        view: '5.284.614',
        img: 'https://st.nettruyenco.com/data/comics/127/toan-chuc-phap-su.jpg',
        href: '',
    },
    {
        id: 7,
        name: 'Trên Người Ta Có Một Con Rồng',
        chapter: '519',
        view: '5.223.133',
        img: 'https://st.nettruyenco.com/data/comics/172/tren-nguoi-ta-co-mot-con-rong.jpg',
        href: '',
    },
];

export default TopMonth;
