const listComic = [
    {
        name: 'Hoa Sơn Tái Xuất',
        img: 'http://st.nettruyenco.com/data/comics/11/hoa-son-tai-xuat.jpg',
        link: '/truyen-tranh/hoa-son-tai-xuat',
        chapterNew: '145',
        timeNew: '2 phút trước',
        view: '14.004.789',
        heart: '5036',
        comment: '6226',
        hot: 'hot',
    },
    {
        name: 'Streamer Pháp Sư',
        img: 'http://st.nettruyenco.com/data/comics/39/streamer-phap-su.jpg',
        link: '/truyen-tranh/streamer-phap-su',
        chapterNew: '289',
        timeNew: '3 giờ trước',
        view: '58.244.262',
        heart: '753.432',
        comment: '54.786',
        hot: 'hot',
    },
    {
        name: 'Tu Tiên Đại Chiến Siêu Năng Lực',
        img: 'http://st.nettruyenco.com/data/comics/212/tu-tien-gia-dai-chien-sieu-nang-luc.jpg',
        link: '/truyen-tranh/tu-tien-gia-dai-chien-sieu-nang-luc',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Là Tà Đế',
        img: 'http://st.nettruyenco.com/data/comics/161/ta-la-ta-de.jpg',
        link: '/truyen-tranh/ta-la-ta-de',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Trời Sinh Đã Là Nhân Vật Phản Diện',
        img: 'http://st.nettruyenco.com/data/comics/235/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg',
        link: '/truyen-tranh/ta-troi-sinh-da-la-nhan-vat-phan-dien',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Chư Giới Tận Thế Online',
        img: 'http://st.nettruyenco.com/data/comics/78/chu-gioi-tan-the-online.jpg',
        link: '/truyen-tranh/chu-gioi-tan-the-online',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Đại Quản Gia Là Ma Hoàng',
        img: 'http://st.nettruyenco.com/data/comics/188/dai-quan-gia-la-ma-hoang.jpg',
        link: '/truyen-tranh/dai-quan-gia-la-ma-hoang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Bắc Kiếm Giang Hồ',
        img: 'http://st.nettruyenco.com/data/comics/47/bac-kiem-giang-ho.jpg',
        link: '/truyen-tranh/bac-kiem-giang-ho',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    //------------------------
    {
        name: 'Hoa Sơn Tái Xuất',
        img: 'http://st.nettruyenco.com/data/comics/11/hoa-son-tai-xuat.jpg',
        link: '/truyen-tranh/hoa-son-tai-xuat',
        chapterNew: '145',
        timeNew: '2 phút trước',
        view: '14.004.789',
        heart: '5036',
        comment: '6226',
        hot: 'hot',
    },
    {
        name: 'Streamer Pháp Sư',
        img: 'http://st.nettruyenco.com/data/comics/39/streamer-phap-su.jpg',
        link: '/truyen-tranh/streamer-phap-su',
        chapterNew: '289',
        timeNew: '3 giờ trước',
        view: '58.244.262',
        heart: '753.432',
        comment: '54.786',
        hot: 'hot',
    },
    {
        name: 'Tu Tiên Đại Chiến Siêu Năng Lực',
        img: 'http://st.nettruyenco.com/data/comics/212/tu-tien-gia-dai-chien-sieu-nang-luc.jpg',
        link: '/truyen-tranh/tu-tien-gia-dai-chien-sieu-nang-luc',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Là Tà Đế',
        img: 'http://st.nettruyenco.com/data/comics/161/ta-la-ta-de.jpg',
        link: '/truyen-tranh/ta-la-ta-de',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Trời Sinh Đã Là Nhân Vật Phản Diện',
        img: 'http://st.nettruyenco.com/data/comics/235/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg',
        link: '/truyen-tranh/ta-troi-sinh-da-la-nhan-vat-phan-dien',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Chư Giới Tận Thế Online',
        img: 'http://st.nettruyenco.com/data/comics/78/chu-gioi-tan-the-online.jpg',
        link: '/truyen-tranh/chu-gioi-tan-the-online',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Đại Quản Gia Là Ma Hoàng',
        img: 'http://st.nettruyenco.com/data/comics/188/dai-quan-gia-la-ma-hoang.jpg',
        link: '/truyen-tranh/dai-quan-gia-la-ma-hoang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Bắc Kiếm Giang Hồ',
        img: 'http://st.nettruyenco.com/data/comics/47/bac-kiem-giang-ho.jpg',
        link: '/truyen-tranh/bac-kiem-giang-ho',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    //------------------------
    {
        name: 'Hoa Sơn Tái Xuất',
        img: 'http://st.nettruyenco.com/data/comics/11/hoa-son-tai-xuat.jpg',
        link: '/truyen-tranh/hoa-son-tai-xuat',
        chapterNew: '145',
        timeNew: '2 phút trước',
        view: '14.004.789',
        heart: '5036',
        comment: '6226',
        hot: 'hot',
    },
    {
        name: 'Streamer Pháp Sư',
        img: 'http://st.nettruyenco.com/data/comics/39/streamer-phap-su.jpg',
        link: '/truyen-tranh/streamer-phap-su',
        chapterNew: '289',
        timeNew: '3 giờ trước',
        view: '58.244.262',
        heart: '753.432',
        comment: '54.786',
        hot: 'hot',
    },
    {
        name: 'Tu Tiên Đại Chiến Siêu Năng Lực',
        img: 'http://st.nettruyenco.com/data/comics/212/tu-tien-gia-dai-chien-sieu-nang-luc.jpg',
        link: '/truyen-tranh/tu-tien-gia-dai-chien-sieu-nang-luc',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Là Tà Đế',
        img: 'http://st.nettruyenco.com/data/comics/161/ta-la-ta-de.jpg',
        link: '/truyen-tranh/ta-la-ta-de',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Trời Sinh Đã Là Nhân Vật Phản Diện',
        img: 'http://st.nettruyenco.com/data/comics/235/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg',
        link: '/truyen-tranh/ta-troi-sinh-da-la-nhan-vat-phan-dien',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Chư Giới Tận Thế Online',
        img: 'http://st.nettruyenco.com/data/comics/78/chu-gioi-tan-the-online.jpg',
        link: '/truyen-tranh/chu-gioi-tan-the-online',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Đại Quản Gia Là Ma Hoàng',
        img: 'http://st.nettruyenco.com/data/comics/188/dai-quan-gia-la-ma-hoang.jpg',
        link: '/truyen-tranh/dai-quan-gia-la-ma-hoang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Bắc Kiếm Giang Hồ',
        img: 'http://st.nettruyenco.com/data/comics/47/bac-kiem-giang-ho.jpg',
        link: '/truyen-tranh/bac-kiem-giang-ho',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    //------------------------
    {
        name: 'Hoa Sơn Tái Xuất',
        img: 'http://st.nettruyenco.com/data/comics/11/hoa-son-tai-xuat.jpg',
        link: '/truyen-tranh/hoa-son-tai-xuat',
        chapterNew: '145',
        timeNew: '2 phút trước',
        view: '14.004.789',
        heart: '5036',
        comment: '6226',
        hot: 'hot',
    },
    {
        name: 'Streamer Pháp Sư',
        img: 'http://st.nettruyenco.com/data/comics/39/streamer-phap-su.jpg',
        link: '/truyen-tranh/streamer-phap-su',
        chapterNew: '289',
        timeNew: '3 giờ trước',
        view: '58.244.262',
        heart: '753.432',
        comment: '54.786',
        hot: 'hot',
    },
    {
        name: 'Tu Tiên Đại Chiến Siêu Năng Lực',
        img: 'http://st.nettruyenco.com/data/comics/212/tu-tien-gia-dai-chien-sieu-nang-luc.jpg',
        link: '/truyen-tranh/tu-tien-gia-dai-chien-sieu-nang-luc',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Là Tà Đế',
        img: 'http://st.nettruyenco.com/data/comics/161/ta-la-ta-de.jpg',
        link: '/truyen-tranh/ta-la-ta-de',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Trời Sinh Đã Là Nhân Vật Phản Diện',
        img: 'http://st.nettruyenco.com/data/comics/235/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg',
        link: '/truyen-tranh/ta-troi-sinh-da-la-nhan-vat-phan-dien',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Chư Giới Tận Thế Online',
        img: 'http://st.nettruyenco.com/data/comics/78/chu-gioi-tan-the-online.jpg',
        link: '/truyen-tranh/chu-gioi-tan-the-online',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Đại Quản Gia Là Ma Hoàng',
        img: 'http://st.nettruyenco.com/data/comics/188/dai-quan-gia-la-ma-hoang.jpg',
        link: '/truyen-tranh/dai-quan-gia-la-ma-hoang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Bắc Kiếm Giang Hồ',
        img: 'http://st.nettruyenco.com/data/comics/47/bac-kiem-giang-ho.jpg',
        link: '/truyen-tranh/bac-kiem-giang-ho',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    //------------------------
    {
        name: 'Hoa Sơn Tái Xuất',
        img: 'http://st.nettruyenco.com/data/comics/11/hoa-son-tai-xuat.jpg',
        link: '/truyen-tranh/hoa-son-tai-xuat',
        chapterNew: '145',
        timeNew: '2 phút trước',
        view: '14.004.789',
        heart: '5036',
        comment: '6226',
        hot: 'hot',
    },
    {
        name: 'Streamer Pháp Sư',
        img: 'http://st.nettruyenco.com/data/comics/39/streamer-phap-su.jpg',
        link: '/truyen-tranh/streamer-phap-su',
        chapterNew: '289',
        timeNew: '3 giờ trước',
        view: '58.244.262',
        heart: '753.432',
        comment: '54.786',
        hot: 'hot',
    },
    {
        name: 'Tu Tiên Đại Chiến Siêu Năng Lực',
        img: 'http://st.nettruyenco.com/data/comics/212/tu-tien-gia-dai-chien-sieu-nang-luc.jpg',
        link: '/truyen-tranh/tu-tien-gia-dai-chien-sieu-nang-luc',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Là Tà Đế',
        img: 'http://st.nettruyenco.com/data/comics/161/ta-la-ta-de.jpg',
        link: '/truyen-tranh/ta-la-ta-de',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Ta Trời Sinh Đã Là Nhân Vật Phản Diện',
        img: 'http://st.nettruyenco.com/data/comics/235/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg',
        link: '/truyen-tranh/ta-troi-sinh-da-la-nhan-vat-phan-dien',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Chư Giới Tận Thế Online',
        img: 'http://st.nettruyenco.com/data/comics/78/chu-gioi-tan-the-online.jpg',
        link: '/truyen-tranh/chu-gioi-tan-the-online',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Đại Quản Gia Là Ma Hoàng',
        img: 'http://st.nettruyenco.com/data/comics/188/dai-quan-gia-la-ma-hoang.jpg',
        link: '/truyen-tranh/dai-quan-gia-la-ma-hoang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
    {
        name: 'Bắc Kiếm Giang Hồ',
        img: 'http://st.nettruyenco.com/data/comics/47/bac-kiem-giang-ho.jpg',
        link: '/truyen-tranh/bac-kiem-giang-ho',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
        hot: 'hot',
    },
];

export default listComic;
