const listComic = [
    {
        name: 'Trọng sinh đô thị tu tiên',
        img: '//st.nettruyenco.com/data/comics/89/chuong-mon-khiem-ton-chut.jpg',
        link: '/truyen-tranh/trong-sinh-do-thi-tu-tien',
        chapterNew: '145',
        timeNew: '2 phút trước',
        view: '14.004.789',
        heart: '5036',
        comment: '6226',
    },
    {
        name: 'Yêu thần kí',
        img: 'http://st.nettruyenco.com/data/comics/85/yeu-than-ky.jpg',
        link: '/truyen-tranh/yeu-than-ki',
        chapterNew: '289',
        timeNew: '3 giờ trước',
        view: '58.244.262',
        heart: '753.432',
        comment: '54.786',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/87/het-nhu-han-quang-gap-nang-gat.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/87/het-nhu-han-quang-gap-nang-gat.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/87/het-nhu-han-quang-gap-nang-gat.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/87/het-nhu-han-quang-gap-nang-gat.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/87/het-nhu-han-quang-gap-nang-gat.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/87/het-nhu-han-quang-gap-nang-gat.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
];

export default listComic;
