const listComic = [
    {
        name: 'Hoa Sơn Tái Xuất',
        img: 'http://st.nettruyenco.com/data/comics/11/hoa-son-tai-xuat.jpg',
        link: '/truyen-tranh/trong-sinh-do-thi-tu-tien',
        chapterNew: '145',
        timeNew: '2 phút trước',
        view: '14.004.789',
        heart: '5036',
        comment: '6226',
    },
    {
        name: 'Yêu thần kí',
        img: 'http://st.nettruyenco.com/data/comics/39/streamer-phap-su.jpg',
        link: '/truyen-tranh/yeu-than-ki',
        chapterNew: '289',
        timeNew: '3 giờ trước',
        view: '58.244.262',
        heart: '753.432',
        comment: '54.786',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/212/tu-tien-gia-dai-chien-sieu-nang-luc.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/161/ta-la-ta-de.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/235/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/78/chu-gioi-tan-the-online.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/188/dai-quan-gia-la-ma-hoang.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
    {
        name: 'Yêu em',
        img: 'http://st.nettruyenco.com/data/comics/47/bac-kiem-giang-ho.jpg',
        link: '/truyen-tranh/nhu-hang-quang-gap-nang',
        chapterNew: '268',
        timeNew: '5 giờ trước',
        view: '600.454.345',
        heart: '90.432',
        comment: '763.432',
    },
];

export default listComic;
